### ISSUE TITLE
一键部署支持

### ISSUE THREAD

**Issue by binggg** [ibearye/talk#3]
在 Github 搜索到了你的项目，看起来挺不错的~~

我这边是云开发 CloudBase Framework 项目（https://github.com/Tencent/cloudbase-framework/ ）的负责人

是否考虑集成一键部署，后面如果合适还可以上架官方的模板和应用中心

方便的话也可以加一下我的微信 cst-being 细聊

**Comment by callmewaynewu** [comment]
🙏首先多谢对这个小项目的肯定。最近还在忙，不过稍微读了一下开发文档，实现起来似乎很简单，等有空了我会进行集成的。
